## Data Analytics using NumPy Assignment

In [1]:
import numpy as np

In [2]:
# 1.Create a rank 2 numpy array of random integers and print:a) shape,size and dimensions of the array b) number of odd and even
#   integers in the array
x = np.array ([[1,2],[3,4]])
type(x)

numpy.ndarray

In [3]:
x.shape

(2, 2)

In [4]:
x.dtype

dtype('int32')

In [5]:
x.size

4

In [6]:
print (x[0,0], x[1,0]) #odd elements

1 3


In [7]:
print (x[0,1],x[1,1]) #even elements

2 4


In [8]:
# 2.Create a (3X3) numpy array with values ranging from 1 to 9.
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# 3.Create a (5X5) random numpy array and print the numbers from the array which are greater than average value of the array.
# Hint: Use np.where() function
z = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print (z)
avg= np.average(z)
print (avg)
num = np.where(z>avg)
print(num)
print("elements which are greater than average value of the array")
print(z[num])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13.0
(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64), array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))
elements which are greater than average value of the array
[14 15 16 17 18 19 20 21 22 23 24 25]


In [10]:
# 4.Given an array of random integers:
arr1 = np.random.randint(50,size=(10,10))
# Find out : a) row wise and column wise mean b) row wise and column wise max and min values c) Variance and Standard Deviation 
# of the array.
arr1
row_mean= np.mean(arr1, axis=0)
print("Mean of each row",row_mean)

col_mean =np.mean(arr1, axis=1)
print("Mean of each column",col_mean)

max_values = np.max(arr1, axis=0)
print("Maximum value of each row",max_values)

min_values = np.min(arr1, axis=1)
print("Minimum Values of each Column",min_values)

varience = np.var(arr1)
print("Varience of the array",varience)

std = np.std(arr1)
print("standard deviation of the array",std)


Mean of each row [30.  29.4 14.3 20.8 18.6 19.2 32.8 34.9 14.2 19.5]
Mean of each column [17.5 26.3 22.9 25.9 20.5 26.4 23.2 20.6 22.4 28. ]
Maximum value of each row [48 48 37 44 43 46 47 46 39 49]
Minimum Values of each Column [0 4 3 2 0 3 5 1 3 1]
Varience of the array 208.93310000000002
standard deviation of the array 14.454518324731545


In [11]:
# Extra Credits
# 5.Given two matrices:
arr1 = np.matrix([[4,5],[7,3]])
arr2 = np.matrix([[2,3],[8,9]])

# Find out the matrix multiplication of the above two matrices without using numpy function and then verify your answer 
# using np.dot(arr1,arr2) function
arr3 = np.multiply(arr1,arr2)
'''res = [[0,0],[0,0]] 
for i in range(len(arr1)): 
    for j in range(len(arr2[0])): 
        for k in range(len(arr2)): 
            result[i][j] += arr1[i][k] * arr2[k][j]
for r in result:
    print(r) '''
result= np.dot(arr1,arr2)
result

matrix([[48, 57],
        [38, 48]])